pipeline {
    agent {
        label 'agent_maven'
    }
    stages {
        stage('Build') {
            steps {
                script {
                    IMAGE = readMavenPom().getArtifactId()
                    VERSION = readMavenPom().getVersion()
                    echo IMAGE
                    echo VERSION
                    sh 'mvn -B -DskipTests clean package'
                    echo "HOLA por aqui andamos"
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
